
mysql: &mysql
  adapter: mysql2
  database: "<%=ENV['OPENSHIFT_APP_NAME']%>"
  username: "<%=ENV['OPENSHIFT_MYSQL_DB_USERNAME']%>"
  password: "<%=ENV['OPENSHIFT_MYSQL_DB_PASSWORD']%>"
  host:     <%=ENV['OPENSHIFT_MYSQL_DB_HOST']%>
  port:     <%=ENV['OPENSHIFT_MYSQL_DB_PORT']%>


defaults: &defaults
  pool: 5
  timeout: 5000
  encoding: utf8
  <<: *<%= ENV['RAILS_DB'] || "mysql" %>

development:
  pool: 5
  timeout: 5000
  encoding: utf8
  adapter: mysql2
  database: smabaches
  username: "root"
  password: "1q2w3e4r5t"
  host: localhost
  port: 3306


test: &test
  pool: 5
  timeout: 5000
  encoding: utf8
  adapter: mysql2
  database: test.smabaches
  username: "root"
  password: "1q2w3e4r5t"
  host: localhost
  port: 3306

production:
  <<: *defaults
