rodriUser = User.new(
  :email                 => "rodri@example.com",
  :password              => "12345678",
  :password_confirmation => "12345678"
)
rodriUser.save!
rodriUser.add_role :admin

estebanUser = User.new(
  :email                 => "esteban@example.com",
  :password              => "12345678",
  :password_confirmation => "12345678"
)
estebanUser.save!
estebanUser.add_role :admin

user = User.new(
  :email                 => "usuario@example.com",
  :password              => "12345678",
  :password_confirmation => "12345678"
)
estebanUser.save!

Publication.create!(title: 'Primera Publicacion',description: 'Bache molesto', author: rodriUser, latitude: -40.1362682 , longitude: -71.29446349999999);
Publication.create!(title: 'Segunda Publiacion',description: 'Bache molesto', author: estebanUser, latitude: -40.14 , longitude: -71.295);
Publication.create!(title: 'Tercera Publicacion',description: 'Bache molesto',author: estebanUser, latitude: -40.15 , longitude: -71.296);

Category.create!(name: 'Bache')
Category.create!(name: 'Graffiti')

Street.create!( name:  '3 DE CABALLERIA')
Street.create!( name:  'CARLOS WEBER')
Street.create!( name:  'DOMINGO RAGUSI')
Street.create!( name:  'ASUNCION FOSBERY')
Street.create!( name:  'JOSE F. CALDERON')
Street.create!( name:  'RUDECINDO ROCA')
Street.create!( name:  'PERITO MORENO')
Street.create!( name:  'TTE. GRAL. ROCA')
Street.create!( name:  'SAN MARTIN')
Street.create!( name:  'GRAL. VILLEGAS')
Street.create!( name:  'GABRIEL OBEID')
Street.create!( name:  'ALTE. BROWN')
Street.create!( name:  'FEDERICO GRAEF')
Street.create!( name:  'JUEZ DEL VALLE')
Street.create!( name:  'CNEL. DIAZ')
Street.create!( name:  'CNEL. ROHDE')
Street.create!( name:  'ANTU_HUE')
Street.create!( name:  'RIVADAVIA')
Street.create!( name:  'MARIANO MORENO')
Street.create!( name:  'EMILIO FREY')
Street.create!( name:  'TTE. CNEL. PEREZ')
Street.create!( name:  'BRIG. J. M. DE ROSAS')
Street.create!( name:  'LOS ABEDULES')
Street.create!( name:  'CAP. DRURY')
Street.create!( name:  'BELGRANO')
Street.create!( name:  'EDUARDO ELORDI')
Street.create!( name:  'SARMIENTO')
Street.create!( name:  'MISIONERO MASCARDI')
Street.create!( name:  'CACIQUE CURRUHUINCA')
Street.create!( name:  'LOS CIPRESES')
Street.create!( name:  'KOESSLER')
Street.create!( name:  'LACAR')
Street.create!( name:  'LOLOG')
Street.create!( name:  '27')
Street.create!( name:  'JULIO C. QUIROGA')
Street.create!( name:  'MAGNO TVETHE')
Street.create!( name:  'CALLE 2')
Street.create!( name:  'VIRGEN DE LAS NIEVES')
Street.create!( name:  'CALLE DEL BOSQUE')
Street.create!( name:  'LAS MUTISIAS')
Street.create!( name:  'LOS HELECHOS')
Street.create!( name:  'LAS LENGAS')
Street.create!( name:  'LOS ALERCES')
Street.create!( name:  'PASAJE LOS SAUCES')
Street.create!( name:  'LAS ORQUIDEAS')
Street.create!( name:  'LOS ROSALES')
Street.create!( name:  'LOS TULIPANES')
Street.create!( name:  'PASAJES ALJABAS')
Street.create!( name:  'PASAJE MICHAI')
Street.create!( name:  'LAS FRUTILLAS')
Street.create!( name:  'LOS LUPINOS')
Street.create!( name:  'LOS ENEBROS')
Street.create!( name:  'LOS PANILES')
Street.create!( name:  'LOS PEHUENES')
Street.create!( name:  'LAS RETAMAS')
Street.create!( name:  'LOS SAUCOS')
Street.create!( name:  'LOS PIÑONES')
Street.create!( name:  'LOS CHAPELES')
Street.create!( name:  'LAS GROSELLAS')
Street.create!( name:  'LOS PINOS')
Street.create!( name:  'LOS MAITENES')
Street.create!( name:  'LOS CEREZOS')
Street.create!( name:  'LAS FRAMBUESAS')
Street.create!( name:  'LOS MAQUIS')
Street.create!( name:  'LOS GUINDOS')
Street.create!( name:  'LAS MOSQUETAS')
Street.create!( name:  'PEDRO ELGUERO')
Street.create!( name:  'PABLO GINGINS')
Street.create!( name:  'DAMIAN ELORRIAGA')
Street.create!( name:  'LOS COIHUES')
Street.create!( name:  'LAS MUTISIAS')
Street.create!( name:  'LAS ARAUCARIAS')
Street.create!( name:  'LOS CALAFATES')
Street.create!( name:  'LOS RAULIES')
Street.create!( name:  'LOS ARRAYANES')
Street.create!( name:  'NONTHUE')
Street.create!( name:  'RUCA CHOROI')
Street.create!( name:  'ALUMINE')
Street.create!( name:  'HUECHULAFQUEN')
Street.create!( name:  'PAIMUN')
Street.create!( name:  'TRAFUL')
Street.create!( name:  'MELIQUINA')
Street.create!( name:  'LOS MANZANOS')
Street.create!( name:  'AMANCAY')
Street.create!( name:  'LOS NOTROS')
Street.create!( name:  'LOS ALAMOS')
Street.create!( name:  'NEUQUEN')
Street.create!( name:  'LANIN')
Street.create!( name:  'CHAPELCO')
Street.create!( name:  'BUENOS AIRES')
Street.create!( name:  'BARTOLOME MITRE')
Street.create!( name:  'ALBERDI')
Street.create!( name:  'CALLEJON GINGINS')
Street.create!( name:  'CALLEJON BELLO NORTE')
Street.create!( name:  'CALLEJON BELLO SUR')
Street.create!( name:  'CALLEJ. TORRES NORTE')
Street.create!( name:  'CALLEJON TORRES SUR')
Street.create!( name:  'CALLEJON CREIDE')
Street.create!( name:  'RAMAYON')
Street.create!( name:  'CORREO APARTADO POSTAL (A.P.)')
Street.create!( name:  'CASILLA CORREO (C.C.)')
Street.create!( name:  'RUTA NAC.40,KM')
Street.create!( name:  'LOS CHILCOS')
Street.create!( name:  'RINCON DEL BOSQUE')
Street.create!( name:  'LOS ROBLES')
Street.create!( name:  'BENITO QUINQUELA MARTIN')
Street.create!( name:  'MOLINA CAMPOS')
Street.create!( name:  'LOS RADALES')
Street.create!( name:  'CASA')
Street.create!( name:  'SIN NOMBRE')
Street.create!( name:  'HEROES DE MALVINAS')
Street.create!( name:  'SUBIDA A BARILOCHE')
Street.create!( name:  'CALLE 25')
Street.create!( name:  'CALLE 4')
Street.create!( name:  'ALDEA DE MONTANA II')
Street.create!( name:  'DEL BOSQUE')
Street.create!( name:  'EL OASIS')
Street.create!( name:  'M.A.CAMINO (COSTANER')
Street.create!( name:  'PIREN')
Street.create!( name:  'AV. COSTANERA')
Street.create!( name:  'CTA.FELIX DE AMADOR')
Street.create!( name:  'QUINTA 61 LOTE Nro.')
Street.create!( name:  'LOS CAUQUENES')
Street.create!( name:  'ALGARROBO')
Street.create!( name:  'CASA NRO.')
Street.create!( name:  'FRACCION NE LOTE NRO')
Street.create!( name:  'CALLE Nº33CH30')
Street.create!( name:  'LAS DIUCAS')
Street.create!( name:  'PABLO NERUDA')
Street.create!( name:  'ALFONSINA STORNI')
Street.create!( name:  'MARCELO BERBEL')
Street.create!( name:  'MIGUEL A.CAMINO')
Street.create!( name:  'HUGO BERBEL')
Street.create!( name:  'JORGE LUIS BORGES')
Street.create!( name:  'ERNESTO SABATO')
Street.create!( name:  'GREGORIO ALVAREZ')
Street.create!( name:  'BERTA KOESSLER')
Street.create!( name:  'MANUEL J.CASTILLA')
Street.create!( name:  'LAS GARZAS')
Street.create!( name:  'LOS PICAFLORES')
Street.create!( name:  'LAS PALOMAS')
Street.create!( name:  'LOS ZORZALES')
Street.create!( name:  'LOS PATOS')
Street.create!( name:  'LAS GOLONDRINAS')
Street.create!( name:  'LAS GAVIOTAS')
Street.create!( name:  'LOS CONDORES')
Street.create!( name:  'LOS CHINGOLOS')
Street.create!( name:  'LOS TEROS')
Street.create!( name:  'LOS COLIBRIES')
Street.create!( name:  'LOS CISNES')
Street.create!( name:  'ANTONIO BERNI')
Street.create!( name:  'LUIS GOÑI')
Street.create!( name:  'ERNESTO LUIS NUÑEZ')
Street.create!( name:  'LA RIOJA')
Street.create!( name:  'RIO NEGRO')
Street.create!( name:  'CHACO')
Street.create!( name:  'SANTA FE')
Street.create!( name:  'SANTIAGO DEL ESTERO')
Street.create!( name:  'CATAMARCA')
Street.create!( name:  'ENTRE RIOS')
Street.create!( name:  'JUJUY')
Street.create!( name:  'LOTE Nro.')
Street.create!( name:  'CERRO CHAPELCO')
Street.create!( name:  'PJE. LAGO HERMOSO')
Street.create!( name:  'EA. CERRO LOS PINOS')
Street.create!( name:  'EA. MIRALEJOS')
Street.create!( name:  'EA. MELIQUINA')
Street.create!( name:  'PJE. PICHI TRAFUL')
Street.create!( name:  'MAITEN')
Street.create!( name:  'MANZANA A')
Street.create!( name:  'MANZANA B')
Street.create!( name:  'MANZANA C')
Street.create!( name:  'MANZANA D')
Street.create!( name:  'MANZANA E')
Street.create!( name:  'MANZANA F')
Street.create!( name:  'MANZANA G')
Street.create!( name:  'MANZANA H')
Street.create!( name:  'RELGUE')
Street.create!( name:  'PJE. TRABUNCO')
Street.create!( name:  'CHACRA 27')
Street.create!( name:  'PJE. PIL PIL')
Street.create!( name:  'PJE. QUILA QUINA')
Street.create!( name:  'PJE. QUECHUQUINA')
Street.create!( name:  'CHIMEHUIN')
Street.create!( name:  'FRANCISCO IBANEZ')
Street.create!( name:  'GUILLERMO VIEIRO')
Street.create!( name:  'CALEUFU')
Street.create!( name:  'PASEO DEL PIONERO')
Street.create!( name:  'PASEO DEL ATARDECER')
Street.create!( name:  'PASEO DEL ENCUENTRO')
Street.create!( name:  'PASEO DE LA VUELTA')
Street.create!( name:  'PASEITO')
Street.create!( name:  'PASEO DE LA LADERA')
Street.create!( name:  'PASEO DEL CEREZO')
Street.create!( name:  'PASEO DEL COLOR')
Street.create!( name:  'PASEO DEL ROBLE')
Street.create!( name:  'PASEO DEL SOL')
Street.create!( name:  'PASEO AITUE')
Street.create!( name:  'PASEO DEL COLEGIO')
Street.create!( name:  'PASEO DEL VIENTO')
Street.create!( name:  'RUTA PROV 62, KM')
Street.create!( name:  'AVDA. MIRADOR')
Street.create!( name:  'PASAJE QUILA-QUINA')
Street.create!( name:  'PASAJE RUCA-NIRE')
Street.create!( name:  'PJE. PUCARA')
Street.create!( name:  'PRIMEROS POBLADORES')
Street.create!( name:  'PJE. YUCO')
Street.create!( name:  'PJE. QUENI')
Street.create!( name:  'PJE. ANGOSTURA')
Street.create!( name:  'PJE. CHACHIN')
Street.create!( name:  'JOSE HERNANDEZ')
Street.create!( name:  'HORACIO QUIROGA')
Street.create!( name:  'PJE. LOLOG')
Street.create!( name:  'TROMEN')
Street.create!( name:  'COPAHUE')
Street.create!( name:  'PIL-PIL')
Street.create!( name:  'ANELO')
Street.create!( name:  'LAS LAJAS')
Street.create!( name:  'LOS ANDES')
Street.create!( name:  'LAS COLORADAS')
Street.create!( name:  'TRAFUL(SUR)')
Street.create!( name:  'TROMEN')
Street.create!( name:  'PASAJE EL PARAISO')
Street.create!( name:  'RUTA PROVINCIAL 62')
Street.create!( name:  'PJE. DEL PARAISO')
Street.create!( name:  'LOLA MORA')
Street.create!( name:  'PILMAYQUEN')
Street.create!( name:  'GERARDO MASANA')
Street.create!( name:  'JULIO SOSA')
Street.create!( name:  'PAPPO NAPOLITANO')
Street.create!( name:  'GABRIEL SAUREL')
Street.create!( name:  'MARTIN M.GUEMES')
Street.create!( name:  'LUCA PRODAN')
Street.create!( name:  'AIME PAINE')
Street.create!( name:  'MOLINA CAMPOS')
Street.create!( name:  'RAUL SOLDI')
Street.create!( name:  'L.SPILIMBERGO')
Street.create!( name:  'F.FADER')
Street.create!( name:  'S.LAURIA')
Street.create!( name:  'R.P.GOMEZ')
Street.create!( name:  'G.VIEIRO')
Street.create!( name:  'QUILLEN')
Street.create!( name:  'YEPUN')
Street.create!( name:  'LIUQUEN')
Street.create!( name:  'HUILEN')
Street.create!( name:  'LOS FRESNOS')
Street.create!( name:  'LOS EUCALIPTUS')
Street.create!( name:  'LOS CEIBOS')
Street.create!( name:  'PASEO PICHI CHACAY')
Street.create!( name:  'PASEO DEL ALBA')
Street.create!( name:  'PASEO DEL CUYEN')
Street.create!( name:  'F.IBANEZ')
Street.create!( name:  'PASEO DE LOS MUSICOS')
Street.create!( name:  'RICARDO GUIRALDES')
Street.create!( name:  'JUAN PABLO TORRES')
Street.create!( name:  'LEOPOLDO LUGONES')
Street.create!( name:  'CERRO. CDTE.DIAZ')
Street.create!( name:  'ALBERTO DE AGOSTINI')
Street.create!( name:  'MELI')
Street.create!( name:  'QUELA')
Street.create!( name:  'PJE. CERRO ABANICO')
Street.create!( name:  'PJE. HUA HUM')
Street.create!( name:  'PJE. LA ISLITA')
Street.create!( name:  'PJE. LAGUNA ROSALES')
Street.create!( name:  'PJE. LAS BANDURRIAS')
Street.create!( name:  'PJE. DE LA PAZ')
Street.create!( name:  'QUECHU')
Street.create!( name:  'EUCALIPTUS')
Street.create!( name:  'MANUEL CHIDIAK')
Street.create!( name:  'GUILLERMO HUDSON')
Street.create!( name:  'PASEO DE LA LUNA')
Street.create!( name:  'EPU')
Street.create!( name:  'GEORG MICIU')
Street.create!( name:  'ANDRES VON PUTTKAMER')
Street.create!( name:  'PASEO NEVADO')
Street.create!( name:  'LOS TORDOS')
Street.create!( name:  'LAS CALANDRIAS')
Street.create!( name:  'EL BIGUÁ')
Street.create!( name:  'LOS PETIRROJOS')
Street.create!( name:  'LUCA PRODAN')
Street.create!( name:  'QUEÑI')
Street.create!( name:  'ESPERANZA')
Street.create!( name:  'LAS MARGARITAS')
Street.create!( name:  'ATAHUALPA YUPANQUI')
Street.create!( name:  'PASAJE EL SOSIEGO')
Street.create!( name:  'LOS ÑIRES')
Street.create!( name:  'LEOPOLDO RODRIGUEZ')
Street.create!( name:  'QUECHUQUINA')
Street.create!( name:  'NUÑEZ')
Street.create!( name:  'DON BOSCO')
Street.create!( name:  'AITUE')
Street.create!( name:  'CHACAY')
Street.create!( name:  'GERMÁN SOPEÑA')
Street.create!( name:  'NANCY SILVESTRINI')
Street.create!( name:  'LINO MORENO')
Street.create!( name:  'CARLOS LORENZANI')
Street.create!( name:  'AILLA')
Street.create!( name:  'MARI')
Street.create!( name:  'CAMINO VIEJO LOLOG')
Street.create!( name:  'PURA')
Street.create!( name:  'CAYU')
Street.create!( name:  'VIOLETA PARRA')
Street.create!( name:  'AV. DE LOS LAGOS')
Street.create!( name:  'CERRO MESA')
Street.create!( name:  'CERRO CURRUHUE')
Street.create!( name:  'CERRO ASERET')
Street.create!( name:  'CERRO BAYO')
Street.create!( name:  'CERRO LOS ANGELES')
Street.create!( name:  'CALLE Nº9 CH30')
Street.create!( name:  'CERRO BELLA VISTA')
Street.create!( name:  'CERRO AZUL')
Street.create!( name:  'CALLE Nº2 CH30')
Street.create!( name:  'CALLE Nº5 CH30')
Street.create!( name:  'CALLE Nº4 CH30')
Street.create!( name:  'CALLE Nº3 CH30')
Street.create!( name:  'CALLE Nº13 CH30')
Street.create!( name:  'CERRO DE LA VIRGEN')
Street.create!( name:  'CERRO BANDURRIAS')
Street.create!( name:  'CERRO VENTANA')
Street.create!( name:  'CERRO ESCALONADO')
Street.create!( name:  'CERRO WAYLE')
Street.create!( name:  'CERRO MOCHO')
Street.create!( name:  'VOLCAN DOMUYO')
Street.create!( name:  'CALLE Nº26 CH30')
Street.create!( name:  'VOLCAN HUANQUIHUE')
Street.create!( name:  'CALLE Nº28 CH30')
Street.create!( name:  'VOLCAN LANIN')
Street.create!( name:  'CERRO COLORADO')
Street.create!( name:  'CALLE Nº21 CH30')
Street.create!( name:  'CALLE Nº23 CH30')
Street.create!( name:  'CALLE Nº25 CH30')
Street.create!( name:  'CALLE Nº36 CH30')
Street.create!( name:  'CALLE Nº27 CH30')
Street.create!( name:  'CALLE Nº 1 LM')
Street.create!( name:  'CALLE Nº2 LM')
Street.create!( name:  'CALLE Nº3 LM')
Street.create!( name:  'CALLE Nº4 LM')
Street.create!( name:  'CALLE Nº5 LM')
Street.create!( name:  'GABRIELA SOBARZO DE GONZALEZ')
Street.create!( name:  'CALLE Nº1 SL')
Street.create!( name:  'CALLE Nº 1 LR')
Street.create!( name:  'CALLE Nº2 LR')
Street.create!( name:  'CALLE Nº3 LR')
Street.create!( name:  'CALLE Nº4 LR')
Street.create!( name:  'CALLE Nº5 LR')
Street.create!( name:  'CALLE Nº6 LR')
Street.create!( name:  'CALLEJON DE SALAZAR')
Street.create!( name:  'JOSE D. PELLETIERI')
Street.create!( name:  'RUTA PROV. Nº19')
Street.create!( name:  'CLUB LACAR')
Street.create!( name:  'CALLE Nº9 CH28')
Street.create!( name:  'PASAJE TRAHUNCO')
Street.create!( name:  'CALLEJON DE TORRES')
Street.create!( name:  'LORENZANI')
Street.create!( name:  'CALLE Nº10 CH28')
Street.create!( name:  'CALLEJON DE BELLO')
Street.create!( name:  'CALLE FUERA DE LA LOCALIDAD')
Street.create!( name:  'BIBLIOTECAS POPULARES')
Street.create!( name:  'CALLE Nº1 PLR')
Street.create!( name:  'CALLE Nº2 PLR')
Street.create!( name:  'CALLE Nº3 PLR')
Street.create!( name:  'CALLE Nº4 PLR')
Street.create!( name:  'S/NOMBRECH2')
Street.create!( name:  'MIGUEL ABUELO')
Street.create!( name:  'ASTOR PIAZZOLA')
Street.create!( name:  'AVDA. CORACEROS GRAL. LAVALLE')
Street.create!( name:  'RUTA ALTERNATIVA SUR')
Street.create!( name:  'CALLE Nº1 CH19')
Street.create!( name:  'CALLE Nº2CH19')
Street.create!( name:  'PJE. MAIPU')
Street.create!( name:  'CALLE Nº1 CH28')
Street.create!( name:  'CALLE Nº 2CH28')
Street.create!( name:  'CALLE Nº 3 CH28')
Street.create!( name:  'CALLE Nº4 CH28')
Street.create!( name:  'CALLE Nº5 CH28')
Street.create!( name:  'CALLE Nº6 CH28')
Street.create!( name:  'CALLE Nº7 CH28')
Street.create!( name:  'CALLE Nº8 CH28')
Street.create!( name:  'CALLE Nº11 CH28')
Street.create!( name:  'CALLE Nº12 CH28')
Street.create!( name:  'CALLE Nº13 CH28')
Street.create!( name:  'CALLE Nº14 CH28')
Street.create!( name:  'CALLE Nº15 CH28')
Street.create!( name:  'CALLE Nº16 CH28')
Street.create!( name:  'CALLE Nº17 CH28')
Street.create!( name:  'CALLE Nº 18 CH28')
Street.create!( name:  'CALLE Nº 19 CH28')
Street.create!( name:  'CALLE Nº 20 CH28')
Street.create!( name:  'CALLE Nº21 CH28')
Street.create!( name:  'CALLE DEL BOSQUE SUR')
Street.create!( name:  'CALLE S/NOMBRE VPAUR')
Street.create!( name:  'ANTONIO "NINO" RAGUSSI')
Street.create!( name:  'SUNAMA ISLA')
Street.create!( name:  'CALLE Nº29 CH30')
Street.create!( name:  'CALLE Nº38 CH30')
Street.create!( name:  'CALLE Nº40 CH30')
Street.create!( name:  'JUAN GONZALEZ VERA')
Street.create!( name:  'RN 40 KM')
Street.create!( name:  'LUIS ALBERTO SPINETTA')
Street.create!( name:  'OSVALDO PUGLIESE')
Street.create!( name:  'LOLITA TORRES')
Street.create!( name:  'ENRIQUE SANTOS DISCEPOLO')
Street.create!( name:  'CELIA CRUZ')
Street.create!( name:  'MARIA ELENA WALSH')
Street.create!( name:  'S/NOMBRE RUCA-HUE ALTO')
Street.create!( name:  'OSCAR MATUS')
Street.create!( name:  'AMANCAY SUR')
Street.create!( name:  'RUTA PROV. Nº48')
Street.create!( name:  'CAMINO VECINAL (LOLOG)')
Street.create!( name:  'PASEO DEL MORRO 1')
Street.create!( name:  'PASEO DEL MORRO 2')
Street.create!( name:  'CALLE Nº1 (CH32)')
Street.create!( name:  'DEL BOSQUE SUR')
Street.create!( name:  'CALLE Nº 3 CH.32')
Street.create!( name:  'CALLE Nº40 CH30')
Street.create!( name:  'JUAN CARLOS FONTANIVE')
Street.create!( name:  'HERNAN DONADIO')
Street.create!( name:  'DR. QUIRNO COSTA')
Street.create!( name:  'CALLE Nº1 LV')
Street.create!( name:  'CALLE Nº9 CH32')
Street.create!( name:  'CALLE Nº2 CHACRA 26')
